### PR TITLE
Add ClientInterface

### PR DESCRIPTION
**Pull request by chadicus**
While there exists a Blackhole Connection implementation, adding a ClientInterface will make mocking in unit tests much easier. It will also allow libraries to develop against an abstraction instead of the concrete Client implementation.

### CODE REVIEW

**Comment by domnikl** [comment]
excellent idea! merged it, thx!

**Comment by chadicus** [comment]
@domnikl any timeframe on a release? No rush, just curious

**Comment by domnikl** [comment]
@chadicus 5 minutes ;)

**Comment by domnikl** [comment]
@chadicus release tagged as 2.10.0

**Comment by chadicus** [comment]
@domnikl  Thanks so much.

**Pull request merged**
