### PR TITLE
Overwrite $sampleRate before checking whether to send this request

### PR DESCRIPTION
**Pull request by Minnozz**
Fixes domnikl/statsd-php#30

### CODE REVIEW

**Comment by domnikl** [comment]
Tests are failing for this one, could you please fix it, so I can merge it in?

**Comment by domnikl** [comment]
https://travis-ci.org/domnikl/statsd-php/jobs/69106535

**Comment by Minnozz** [comment]
The tests that fail seem invalid to me, because they assume that the metric will be sent through the connection even though there is a chance that it is "sampled away". Do you agree?

**Comment by domnikl** [comment]
Anyway we need to fix the tests, maybe there is another solution to define what gets sampled away and what not. A separate class to do the random number generation that could be stubbed would do the job. We can't just delete the tests.

**Comment by domnikl** [comment]
Closing because of inactivity and conflicts.

**Pull request closed without merging**
